### ISSUE TITLE
Example for 2D Triangulation

### ISSUE THREAD

**Issue by fhaag** [DesignEngrLab/TVGL#27]
Hello,

I've tried to generate a 2D triangulation with this library, but I can't seem to figure out how to use `TVGL.TriangulatePolygon.Run2D`:

```c#
var points = new[]
{
	new List<TVGL.Point>
	{
		new TVGL.Point(1, 1),
		new TVGL.Point(1, 5),
		new TVGL.Point(5, 5),
		new TVGL.Point(5, 1)
	}
};

var isPositive = vertices.Select(vl => false).ToArray();
var orderedPoints = TVGL.TriangulatePolygon.OrderLoops2D(points, ref isPositive).Select(l => l.ToArray()).ToArray();

List<List<int>> groupsOfLoops;
var triangles = TVGL.TriangulatePolygon.Run2D(orderedPoints,
	out groupsOfLoops,
	ref isPositive);
```

So, this is my attempt to triangulate a rectangle, but `Run2D` always throws an exception with the message "Triangulation failed after 3 attempts."

Is there anything I'm doing wrong?

Thanks in advance!

P.S.: For what it's worth, I did manage to get a valid triangulation of concave polygons with holes from the `TVGL.TriangulatePolygon.Run` method. The only times I'm getting the "Triangulation failed after 3 attempts." message from `Run` is when the polygon has intersecting edges, or if I pass in a "polygon" with less than three vertices (none of which will happen in my actual use case).

**Comment by massonib** [comment]
The function was built to patch flat holes in a tessellated solid, after slicing it in half. The output triangles for this function are a list of list of **vertex** arrays, where each array is three vertices that make up a triangle. Therefore, the points need to have been created with a vertex reference. It is failing when trying to create the triangles because it want's to use Point.Reference[0] (around line 1557), which is a vertex. Using TVGL.TriangulatePolygon.Run projects the vertices into points, assigning each point a vertex reference. See example: 

                var vertices = new[]
                {
                    new List<TVGL.Vertex>
                    {
                        new TVGL.Vertex(new []{1, 1, 0.0}),
                        new TVGL.Vertex(new []{5, 1, 0.0}),
                        new TVGL.Vertex(new []{5, 5, 0.0}),
                        new TVGL.Vertex(new []{1, 5, 0.0})
                    }
                };

                var isPositive = vertices.Select(vl => false).ToArray();
                var normal = new[] {0, 0, 1.0};
                var triangles = TVGL.TriangulatePolygon.Run(vertices, normal);

P.S.: The method is not built to handle self-intersecting polygons.
